version: 2

formats:
  - epub
  - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

sphinx:
   configuration: docs/conf.py

python:
  version: "3.7"
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt  