version: 2

formats:
  - epub
  - pdf

sphinx:
  configuration: docs/conf.py

python:
  version: "3.8"
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .
